# Generated by Django 3.0.5 on 2021-03-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doclib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedoc',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
